import axios from "axios";
import { useToast } from "@chakra-ui/react";
import React from "react";
import { Box, Image, Heading, Button } from "@chakra-ui/react";
import { useRouter } from "next/router";
import Head from "next/head";

const Page = ({ movieData }) => {
  const toast = useToast();
  const { id, Title, Images, Poster } = movieData;
  const router = useRouter();

  const HandleGoBackButton = () => {
    router.back();
    toast({
      title: "Go Back",
      description: "Successfully",
      status: "success",
      duration: 2000,
      isClosable: true,
    });
  };
  return (
    <Box
      display={"flex"}
      justifyContent="center"
      alignItems={"center"}
      flexDirection="column"
    >
      <Head>
        <title>Single Page Movie Detail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading as={"h2"}>{"Single Page Movie Data"}</Heading>
      <Box
        key={id}
        border="0px solid red"
        display={"flex"}
        flexDirection="column"
        width="350px"
        textAlign={"center"}
        alignItems="center"
        padding="1rem"
        bgGradient="radial(gray.300, yellow.400, pink.200)"
        borderRadius={"1rem"}
        marginTop="1rem"
      >
        <Image src={Poster} alt={Title} width={300} height={300} />
        <Heading as={"h3"}>{Title}</Heading>
        <Button onClick={HandleGoBackButton}>Go Back</Button>
      </Box>

      <Box
        display={"grid"}
        gridTemplateColumns="repeat(3,1fr)"
        gap="2rem"
        margin={"auto"}
        marginTop="1rem"
      >
        {Images.map((data) => (
          <Box
            key={data}
            border="0px solid red"
            display={"flex"}
            flexDirection="column"
            width="350px"
            height={"350"}
            textAlign={"center"}
            alignItems="center"
            padding="1rem"
            bgGradient="linear(to-l, #7928CA, #FF0080)"
            borderRadius={"1rem"}
          >
            <Image src={data} width={300} height={300} alt={data} />
          </Box>
        ))}
      </Box>
    </Box>
  );
};

export async function getStaticPaths() {
  let response = await fetch(`https://json-server-mock-main.vercel.app/movies`);

  let data = await response.json();
  return {
    paths: data.map((movie) => ({
      params: { id: movie.id.toString() },
    })),
    fallback: false, // can also be true or 'blocking'
  };
}

export async function getStaticProps(context) {
  const {
    params: { id },
  } = context;

  let response = await axios.get(
    `https://json-server-mock-main.vercel.app/movies/${id}`
  );
  return {
    props: {
      movieData: await response.data,
    },
  };
}

export default Page;
