import Head from "next/head";
import axios from "axios";
import { Box, Button, Heading, Image } from "@chakra-ui/react";
import Link from "next/link";

export default function watchlist({ movieData }) {
  const deleteWatchList = async (id) => {
    alert("Deleted Watchlist Successfully");

    await axios
      .delete(`https://json-server-mock-main.vercel.app/watchlist/${id}`)
      .then((res) => console.log("then", res))
      .catch((err) => console.log("error", err));
  };
  return (
    <div>
      <Head>
        <title>Watch List Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Box display={"flex"} justifyContent="space-around" marginTop={"1rem"}>
          <Heading as={"h1"} textAlign="center">
            Watch List Page
          </Heading>
          <Heading>
            <Link href={"/"}>Go To Home Page</Link>
          </Heading>
        </Box>
        <Box
          display={"grid"}
          gridTemplateColumns="repeat(3,1fr)"
          gap="2rem"
          margin={"auto"}
          marginTop="1rem"
        >
          {movieData.map((movie) => (
            <Box
              key={movie.id}
              border="0px solid red"
              display={"flex"}
              flexDirection="column"
              width="350px"
              textAlign={"center"}
              alignItems="center"
              padding="1rem"
              bgGradient="radial(gray.300, yellow.400, pink.200)"
              borderRadius={"1rem"}
            >
              <Image
                src={movie.Poster}
                alt={movie.Title}
                width={300}
                height={300}
              />
              <Heading as={"h3"}>{movie.Title}</Heading>
              <Box display={"flex"} gap="1rem">
                <Button onClick={() => deleteWatchList(movie.id)}>
                  Delete Watch List
                </Button>
                <Link href={"/"}>
                  {" "}
                  <Button onClick={() => alert("Go Back Successfully")}>
                    Go Back
                  </Button>
                </Link>
              </Box>
            </Box>
          ))}
        </Box>
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  let response = await axios.get(
    `https://json-server-mock-main.vercel.app/watchlist`
  );

  return {
    props: {
      movieData: await response.data,
    }, // will be passed to the page component as props
  };
}
